USE ADO10;
GO 
CREATE PROCEDURE ShowBook AS 
SELECT  BOOK.title AS TITLE, AUTHOR.last_name AS AUTHOR, PUBLISHER.name AS PUBLISHER FROM BOOK JOIN AUTHOR ON BOOK.author_key=AUTHOR.id
   		JOIN PUBLISHER ON BOOK.publisher_key=PUBLISHER.id 
