//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int isbn { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string original_language { get; set; }
        public Nullable<int> year_of_release { get; set; }
        public string description { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<bool> is_custom { get; set; }
        public byte[] image { get; set; }
        public string ganre { get; set; }
    }
}
